CREATE TABLE IF NOT EXISTS Tasks (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Description TEXT NOT NULL,
    User TEXT NOT NULL,
    Status INTEGER NOT NULL,
    Priority INTEGER NOT NULL,
    DueDate TEXT NOT NULL,
    Notes TEXT,
    IsActive INTEGER NOT NULL DEFAULT 1
);